package com.ov.producer.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ov.producer.entity.BleCheckRecord;

import com.ov.producer.dao.BleCheckRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bleCheckRecordDaoConfig;

    private final BleCheckRecordDao bleCheckRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bleCheckRecordDaoConfig = daoConfigMap.get(BleCheckRecordDao.class).clone();
        bleCheckRecordDaoConfig.initIdentityScope(type);

        bleCheckRecordDao = new BleCheckRecordDao(bleCheckRecordDaoConfig, this);

        registerDao(BleCheckRecord.class, bleCheckRecordDao);
    }
    
    public void clear() {
        bleCheckRecordDaoConfig.clearIdentityScope();
    }

    public BleCheckRecordDao getBleCheckRecordDao() {
        return bleCheckRecordDao;
    }

}
